exports.xml='<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:NXR:WOI_WorkorderInterface_Create_WS__c">'+
   '<soapenv:Header>'+
      '<urn:AuthenticationInfo>'+
         '<urn:userName>'+woTpl.remedyUsr+'</urn:userName>'+
         '<urn:password>'+woTpl.remedyPwd+'</urn:password>'+
         '<urn:authentication></urn:authentication>'+
         '<urn:locale></urn:locale>'+
         '<urn:timeZone></urn:timeZone>'+
      '</urn:AuthenticationInfo>'+
   '</soapenv:Header>'+
   '<soapenv:Body>'+
      '<urn:WorkOrder_Submit_Service>'+
         '<urn:Status>'+woTpl.woStatus+'</urn:Status>'+
         '<urn:Short_Description>'+woTpl.shortDescr+'</urn:Short_Description>'+
         '<urn:Request_Manager>'+woTpl.requestMgr+'</urn:Request_Manager>'+
         '<urn:Assignee_Groups>'+woTpl.asigneeGrps+'</urn:Assignee_Groups>'+
         '<urn:chr_EmpresaResolutora__c>'+woTpl.empResol+'</urn:chr_EmpresaResolutora__c>'+
         '<urn:Site>'+woTpl.Site+'</urn:Site>'+
         '<urn:CustomerFullName>'+woTpl.custFullName+'</urn:CustomerFullName>'+
         '<urn:Requestor_ID>'+woTpl.reqID+'</urn:Requestor_ID>'+
         '<urn:Requester_Support_Organization>'+woTpl.reqSuppOrg+'</urn:Requester_Support_Organization>'+
         '<urn:Support_Organization>'+woTpl.supportOrg+'</urn:Support_Organization>'+
         '<urn:Request_Assignee>'+woTpl.reqAsignee+'</urn:Request_Assignee>'+
         '<urn:Support_Company>'+woTpl.supportCo+'</urn:Support_Company>'+
         '<urn:KIO_Resolucion>'+woTpl.resolution+'</urn:KIO_Resolucion>'+
         '<urn:Support_Group_Name>'+woTpl.supportGrpName+'</urn:Support_Group_Name>'+
         '<urn:Status_Reason>'+woTpl.statusReason+'</urn:Status_Reason>'+
         '<urn:Detailed_Description>'+woTpl.detailedDescr+'</urn:Detailed_Description>'+
         '<urn:Customer_Middle_Name>'+woTpl.custMiddleName+'</urn:Customer_Middle_Name>'+
         '<urn:WorkOrder_ID>'+woTpl.woID+'</urn:WorkOrder_ID>'+
         '<urn:Work_Order_Type>'+woTpl.woType+'</urn:Work_Order_Type>'+
         '<urn:Priority>'+woTpl.woPriority+'</urn:Priority>'+
         '<urn:Manufacturer__2_>'+woTpl.manufacturer2+'</urn:Manufacturer__2_>'+
         '<urn:Product_Name__2_>'+woTpl.productName2+'</urn:Product_Name__2_>'+
         '<urn:KIO_Reported_Source>'+woTpl.kioRepSrc+'</urn:KIO_Reported_Source>'+
         '<urn:Created_From_flag>'+woTpl.createdFromFlag+'</urn:Created_From_flag>'+
         '<urn:Request_Manager_Company>'+woTpl.reqMgrCo+'</urn:Request_Manager_Company>'+
         '<urn:Product_Cat_Tier_3__2_>'+woTpl.prodCatT3+'</urn:Product_Cat_Tier_3__2_>'+
         '<urn:Product_Cat_Tier_1_2_>'+woTpl.prodCatT1+'</urn:Product_Cat_Tier_1_2_>'+
         '<urn:Product_Cat_Tier_2__2_>'+woTpl.prodCatT2+'</urn:Product_Cat_Tier_2__2_>'+
         '<urn:Customer_Last_Name>'+woTpl.custLastName+'</urn:Customer_Last_Name>'+
         '<urn:Customer_Company>'+woTpl.custCo+'</urn:Customer_Company>'+
         '<urn:Customer_Person_ID>'+woTpl.custPersonID+'</urn:Customer_Person_ID>'+
         '<urn:Customer_First_Name>'+woTpl.custFirstName+'</urn:Customer_First_Name>'+
         '<urn:Customer_Internet_E-mail>'+woTpl.custIntEmail+'</urn:Customer_Internet_E-mail>'+
         '<urn:Customer_Organization>'+woTpl.custOrg+'</urn:Customer_Organization>'+
         '<urn:Customer_Department>'+woTpl.custDept+'</urn:Customer_Department>'+
         '<urn:Last_Name>'+woTpl.lastName+'</urn:Last_Name>'+
         '<urn:First_Name>'+woTpl.firstName+'</urn:First_Name>'+
         '<urn:Middle_Initial>'+woTpl.middleInitial+'</urn:Middle_Initial>'+
         '<urn:Organization>'+woTpl.org+'</urn:Organization>'+
         '<urn:Manager_Support_Organization>'+woTpl.mgrSuppOrg+'</urn:Manager_Support_Organization>'+
         '<urn:Manager_Support_Group_Name>'+woTpl.mgrSuppGrpName+'</urn:Manager_Support_Group_Name>'+
         '<urn:Summary>'+woTpl.shortDescr+'</urn:Summary>'+
         '<urn:Location_Company>'+woTpl.locationCo+'</urn:Location_Company>'+
         '<urn:Categorization_Tier_1>'+woTpl.categoryT1+'</urn:Categorization_Tier_1>'+
         '<urn:Internet_E-mail>'+woTpl.intEmail+'</urn:Internet_E-mail>'+
         '<urn:ddl_Prioridad>'+woTpl.priority+'</urn:ddl_Prioridad>'+
         '<urn:ddl_Urgencia>'+woTpl.urgency+'</urn:ddl_Urgencia>'+
         '<urn:ddl_Impacto>'+woTpl.impact+'</urn:ddl_Impacto>'+
         '<urn:Company>'+woTpl.company+'</urn:Company>'+
         '<urn:Person_ID>'+woTpl.persID+'</urn:Person_ID>'+
         '<urn:z1D_Action>'+woTpl.action+'</urn:z1D_Action>'+
         '<urn:Categorization_Tier_2>'+woTpl.categoryT2+'</urn:Categorization_Tier_2>'+
         '<urn:Categorization_Tier_3>'+woTpl.categoryT3+'</urn:Categorization_Tier_3>'+
         '<urn:Region>'+woTpl.region+'</urn:Region>'+
         '<urn:Site_Group>'+woTpl.siteGrp+'</urn:Site_Group>'+
         '<urn:Department>'+woTpl.dept+'</urn:Department>'+
         '<urn:RequesterLoginID>'+woTpl.reqLoginID+'</urn:RequesterLoginID>'+
         '<urn:Cliente>'+woTpl.cliente+'</urn:Cliente>'+
         '<urn:GrupoSoporteAsignado>'+woTpl.grpSuppAsign+'</urn:GrupoSoporteAsignado>'+
         '<urn:Impact>'+woTpl.impact+'</urn:Impact>'+
         '<urn:Urgency>'+woTpl.urgency+'</urn:Urgency>'+
         '<urn:PrioridadKio>'+woTpl.priority+'</urn:PrioridadKio>'+
         '<urn:submitter>'+woTpl.submitter+'</urn:submitter>'+
      '</urn:WorkOrder_Submit_Service>'+
   '</soapenv:Body>'+
'</soapenv:Envelope>'
